name: map_prototype
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  geolocator: ^13.0.3
  google_maps_flutter: ^2.11.0
  google_places_flutter: ^2.1.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
